# This is a basic workflow to help you get started with Actions

name: NIGHTLY

# Controls when the action will run. 
on:
  # Triggers the workflow at 4:05
  schedule:
    - cron: '05 04 * * *'
    
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  #BUILD DEL MAVEN PACKAGE SIN TESTS
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Clone repository
          uses: actions/checkout@v2
        
        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 11
        
        - name: Build native with Maven
          run: mvn -B package -DskipTests

        - name: Upload jar for next job
          uses: actions/upload-artifact@v2
          with:
            name: target
            path: target

  test_selenium:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # STEP CHECKOUT 
      - name: Checkout commit 
        uses: actions/checkout@v2
        #with:
         #ref: 'dev'
        
        # INSTALAR JAVA  
      - name: Set up JDK 11 
        uses: actions/setup-java@v1
        with:
          java-version: 11
            
        # TEST E2E SELENIUM 
      - name: Maven Build TEST SELENIUM
        run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.selenium.*Test' test
  
  test_rest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # STEP CHECKOUT 
      - name: Checkout commit 
        uses: actions/checkout@v2
        #with:
         #ref: 'dev'
        
        # INSTALAR JAVA  
      - name: Set up JDK 11 
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
        # TEST E2E REST
      - name: Maven Build TEST REST
        run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.rest.*Test' test

  test_unitario:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # STEP CHECKOUT 
      - name: Checkout commit 
        uses: actions/checkout@v2
        #with:
         #ref: 'dev'
        
        # INSTALAR JAVA  
      - name: Set up JDK 11 
        uses: actions/setup-java@v1
        with:
          java-version: 11
        # TEST UNITARIOS
      - name: Maven Build TEST UNITARIO
        run: mvn -B '-Dtest=es.urjc.code.daw.library.unitary.*Test' test
  


 #DOCKER BUILD 
  docker:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    
      - name: Clone repository
        uses: actions/checkout@v2
    
      - name: Download Jar from previous job
        uses: actions/download-artifact@v2
        with:
          name: target
      
      - name: Generate tag
        run: echo ::set-output name=tag::$(date +'%Y%m%d.%H%M%S')
        id: project
      
      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
      
      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/items:${{ steps.project.outputs.tag }} .
      
      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/items:${{ steps.project.outputs.tag }}
